-- NOICE.NVIM COMPATIBILITY ISSUE (2026-01-04)
-- ============================================
-- Problem: Pressing ":" crashes Neovim immediately (no clean exit, just crash)
--
-- Root cause: noice.nvim uses vim.ui_attach API which has bugs in Neovim
-- - Neovim Issue #31726: crashes after nvim_ui_attach call
--   https://github.com/neovim/neovim/issues/31726
-- - noice.nvim Issue #1036: confirm prompts broken on 0.11
--   https://github.com/folke/noice.nvim/issues/1036
--
-- Environment: macOS (Apple Silicon)
--
-- Tested combinations (ALL CRASH):
-- - Neovim 0.11.5 (brew) + noice.nvim 7bfd942 (latest) - CRASHES
-- - Neovim 0.11.5 + noice.nvim 0427460 (Sep 2025) - CRASHES
-- - Neovim 0.12.0-dev (nightly, Jan 3 2026) + noice.nvim - CRASHES
-- - Neovim 0.12.0-dev + noice + blink.cmp disabled - CRASHES
-- - Neovim 0.12.0-dev + noice + blink.cmp cmdline disabled - CRASHES
-- - Outside of tmux (fresh terminal) - CRASHES
--
-- Ruled out as causes:
-- - blink.cmp (tested disabled)
-- - tmux (tested outside tmux)
-- - noice version (tested old and new)
-- - Neovim version (tested 0.11.5 and 0.12.0-dev)
--
-- Conclusion: Bug is specific to noice.nvim + macOS Apple Silicon.
-- Likely a vim.ui_attach issue in Neovim's macOS ARM build.
--
-- Workaround: Disable noice.nvim entirely. Cmdline appears at bottom (native).
--
-- TO RE-ENABLE: Monitor these issues for fixes:
-- - https://github.com/neovim/neovim/issues/31726
-- - https://github.com/folke/noice.nvim/issues
-- Then test pressing ":" - if it crashes, re-enable this disable
--
-- Debug tool: require("config.debug-keys") in init.lua
-- Log location: ~/.cache/nvim/keypress-debug.log

-- ACTUAL FIX (2026-01-04): Full laptop restart resolved the issue.
--
-- What did NOT work:
-- - Restarting Ghostty terminal
-- - Killing tmux sessions
-- - Switching Neovim versions
-- - Disabling plugins
--
-- What worked: Full macOS system restart
--
-- The crash was likely caused by stale system state (possibly macOS input
-- subsystem, WindowServer, or low-level terminal I/O that only a full
-- reboot clears).
--
-- Lesson learned: For bizarre crashes that defy all debugging, try a full
-- system restart before spending hours on plugin/config debugging.
--
-- noice.nvim is now working normally with no configuration changes needed.

return {}
